                target_table="application_logs",
            ),
            CleanupTask(
                task_id="cleanup_old_sessions",
                task_type="database",
                description="Delete expired user sessions",
                retention_days=30,
                target_table="user_sessions",
            ),
            CleanupTask(
                task_id="cleanup_temp_files",
                task_type="filesystem",
                description="Delete temporary files",
                retention_days=self.temp_file_retention_days,
                target_directory="/tmp/app_temp",
            ),
            CleanupTask(
                task_id="cleanup_old_reports",
                task_type="filesystem",
                description="Delete old generated reports",
                retention_days=self.report_file_retention_days,
                target_directory="/tmp/reports",
            ),
            CleanupTask(
                task_id="cleanup_failed_tasks",
                task_type="database",
                description="Delete old failed tasks",
                retention_days=240,
                target_table="tasks",
            ),
